# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lexuan Wang 
email: wanglexuan@cuc.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: contrast
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
# permalink: /about/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
#   - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Chang Zhang"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "\ 
  Communication University of China \ \n
  School of Government and Public Affairs \ \n
  Department of Political Communication \ \n"

  Email: "changzhang@cuc.edu.cn"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:changzhang@cuc.edu.cn"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=CYxRAnAAAAAJ&hl=en&authuser=1"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Chang-Zhang-2?ev=hdr_xprf&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6Il9kaXJlY3QiLCJwYWdlIjoiaG9tZSIsInByZXZpb3VzUGFnZSI6Il9kaXJlY3QiLCJwb3NpdGlvbiI6Imdsb2JhbEhlYWRlciJ9fQ"


footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:changzhang@cuc.edu.cn"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: " https://scholar.google.com/citations?user=CYxRAnAAAAAJ&hl=en&authuser=1"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Chang-Zhang-2?ev=hdr_xprf&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6Il9kaXJlY3QiLCJwYWdlIjoiaG9tZSIsInByZXZpb3VzUGFnZSI6Il9kaXJlY3QiLCJwb3NpdGlvbiI6Imdsb2JhbEhlYWRlciJ9fQ"

defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
